# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae008ea822293bb07e4bd4ab6f64130de49725a21177fa31841004c7e2a5fd41588de7a3bf9a1e9970411124bb206b97468a1ba2cbf949e34a3a832f99d90a1

test:
  secret_key_base: f9a0220ec74c25ef27fa682b1455b324790778a72030fc6909fce0de287a77bf2aa495a056691b7fba779355fe9b6eb12bc391966ca59c0265cabb1322fa1bda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
